CREATE TABLE IF NOT EXISTS jwt_whitelist
(
        USERNAME VARCHAR(255) NOT NULL UNIQUE,
        PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO jwt_whitelist (USERNAME, PASSWORD)
VALUES
        ('TESTUSER1', 'TESTPASSWORD1'),
        ('TESTUSER2', 'TESTPASSWORD2');